_target_: src.models.mdxnet.ConvTDFNet

target_name: 'other'

# model
num_blocks: 11
l: 3
g: 48
k: 3
bn: 8
bias: False

# stft
n_fft: 7682
dim_f: 3072
dim_t: 256
dim_c: 4
hop_length: 1024

overlap: 4096

# optimizer
lr: 0.00005
optimizer: rmsprop
